config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'bookmarks/new'
  root to: 'lists#index'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  # thats because we dont want to destroy the list
  resources :bookmarks, only: [:destroy]
end

# (create destroy edit index new show update)
# rails g controller lists index show new edit

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, length: { minimum: 1 }, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :overview, presence: true, length: { minimum: 1 }
  validates :title, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def edit
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new movie to <%= @list.name %></h1>

<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.association :movie, as: :select %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<div>
  <%= link_to "Back to the list", list_path(@list) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.pocketwanderings.com/wp-content/uploads/2021/10/Backyard-Cinema-Wandsworth-1-1.jpeg);">
  <div class="container">
  <h1>Watch lists</h1>
  <%= link_to '<a class="btn btn-ghost" href="#">New list</a>'.html_safe, new_list_path %>
  </div>
</div>

<div class="cards">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="card-category">
      <%= list.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Add a new List!</h1>

<%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
<% end %>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="banner">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
<%= link_to "add movie", new_list_bookmark_path(@list) %>
<%= link_to "All lists", lists_path %>
  <div class="row mt-5">
    <div class="cards">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= bookmark.movie.poster_url %>')">
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.movie.overview %></p>
            <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe, bookmark_path(bookmark),
             data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "card-remove-link" %>
          </div>
        <% end %>
    </div>
  </div>
</div>